version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: petmanager-postgres
    environment:
      POSTGRES_DB: petmanager_db
      POSTGRES_USER: petmanager_user
      POSTGRES_PASSWORD: petmanager_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - petmanager-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petmanager_user -d petmanager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: petmanager-auth
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petmanager_db
      DB_USERNAME: petmanager_user
      DB_PASSWORD: petmanager_pass
      BREVO_USERNAME: ${BREVO_USERNAME}
      BREVO_PASSWORD: ${BREVO_PASSWORD}
      SENDER_EMAIL: ${SENDER_EMAIL:-camiloloaiza0303@gmail.com}
      SENDER_NAME: ${SENDER_NAME:-PetManager}
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - petmanager-network

  supplier-service:
    build:
      context: .
      dockerfile: supplier-service/Dockerfile
    container_name: petmanager-supplier
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petmanager_db
      DB_USERNAME: petmanager_user
      DB_PASSWORD: petmanager_pass
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - petmanager-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: petmanager-notification
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petmanager_db
      DB_USERNAME: petmanager_user
      DB_PASSWORD: petmanager_pass
      BREVO_SMTP_PASSWORD: ${BREVO_SMTP_PASSWORD}
      SENDER_EMAIL: ${SENDER_EMAIL:-camiloloaiza0303@gmail.com}
      SENDER_NAME: ${SENDER_NAME:-PetManager Notificaciones}
      services.supplier-service.url: http://supplier-service:8082
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      supplier-service:
        condition: service_healthy
    networks:
      - petmanager-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: petmanager-gateway
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - supplier-service
      - notification-service
    networks:
      - petmanager-network

volumes:
  postgres_data:
    driver: local

networks:
  petmanager-network:
    driver: bridge