services:
  - type: web
    name: petmanager-app
    runtime: docker
    repo: https://github.com/camiloloaiza03/pet-manager.git
    branch: main
    dockerfilePath: ./Dockerfile.render
    region: oregon
    plan: free

    # Variables de entorno con credenciales reales
    envVars:
      - key: DB_URL
        value: postgresql://avnadmin:AVNS_SlYBLMRNIYyXuTt1oju@pet-manager-filmverse-db.c.aivencloud.com:10898/defaultdb?sslmode=require
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_SlYBLMRNIYyXuTt1oju
      - key: DB_HOST
        value: pet-manager-filmverse-db.c.aivencloud.com
      - key: DB_PORT
        value: "10898"
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL_MODE
        value: require
      - key: BREVO_USERNAME
        value: 8ddac8001@smtp-brevo.com
      - key: BREVO_SMTP_PASSWORD
        value: wmWysPfqNLzAankx
      - key: BREVO_API_KEY
        value: xkeysib-api-key-placeholder
      - key: SENDER_EMAIL
        value: camiloloaiza0303@gmail.com
      - key: SENDER_NAME
        value: PetManager
      - key: FRONTEND_URL
        value: https://petstore-feat2-front.vercel.app
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_PROFILES_ACTIVE
        value: production

    # Health check
    healthCheckPath: /health

    # Auto-deploy
    autoDeploy: true

    # Configuración de build
    buildCommand: |
      echo "Preparando PetManager para despliegue..."
      chmod +x ./build-and-run.sh || true
      find . -name "mvnw" -exec chmod +x {} \; || true
