server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Configuración CORS global
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://*.vercel.app"
              - "https://*.netlify.app"
              - "https://*.render.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      # Rutas de microservicios
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: supplier-service
          uri: http://localhost:8082
          predicates:
            - Path=/supplier/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Source, api-gateway

# Actuator y logging
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.petmanager.api_gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.web.cors: DEBUG