# ============================================
# CONFIGURACIÓN DE PRODUCCIÓN - SUPPLIER SERVICE
# ============================================

server:
  port: ${PORT:8082}  # Render asigna puerto dinámico vía variable PORT

spring:
  application:
    name: supplier-service

  # ================================================
  # CONFIGURACIÓN DE BASE DE DATOS AIVEN
  # ================================================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # Configuración de conexión para producción
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # ================================================
  # CONFIGURACIÓN JPA/HIBERNATE
  # ================================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Deshabilitado en producción
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  # ================================================
  # CONFIGURACIÓN GRAPHQL
  # ================================================
  graphql:
    schema:
      locations: classpath:/graphql/
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

# ================================================
# CONFIGURACIÓN DE ACTUATOR (MONITOREO)
# ================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# ================================================
# CONFIGURACIÓN DE LOGGING
# ================================================
logging:
  level:
    com.petmanager.supplier_service: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.graphql: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"